# render.yaml – Deploy EmpMS app on Render using Docker

previews:
  generation: automatic  # optional preview environment setup

services:
  - type: web
    name: empl-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    region: oregon
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: empl-db
          property: connectionString

databases:
  - name: empl-db
    plan: basic-256mb
    region: oregon

envVarGroups:
  - name: default-env
    envVars:
      - key: LOG_LEVEL
        value: INFO
