# render.yaml – Blueprint for EMS/Empl project

previews:
  generation: automatic  # optional: enable preview environments for PRs

services:
  - type: web
    name: empl-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    region: oregon
    branch: main
    buildCommand: mvn package
    startCommand: java -jar target/your-app.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: empl-db
          property: connectionString

databases:
  - name: empl-db
    plan: basic-256mb
    region: oregon

envVarGroups:
  - name: default-env
    envVars:
      - key: LOG_LEVEL
        value: INFO
